import type { Lang } from '../../types';

export const SETTINGS_COPY: Record<Lang, Record<string, string>> = {
  en: {
    title: 'SETTINGS',
    section_model: 'PROVIDER & MODEL',
    section_appearance: 'APPEARANCE',
    section_about: 'ABOUT',
    appearance_note: 'Dark mode only · light coming soon',
    version: 'Version',
    github: 'GitHub',
    provider: 'PROVIDER',
    model: 'MODEL',
    base: 'BASE URL',
    key: 'API KEY',
    change_key: 'Change',
    cancel: 'Cancel',
    save: 'SAVE',
    saving: 'Saving…',
    close: 'Close',
    language: 'LANGUAGE',
    no_key: 'No key configured',
    has_key: '•••••••• (stored)',
    custom_model: 'Custom model ID',
    section_mcp: 'MCP SERVERS',
    mcp_add: 'Add Server',
    mcp_name: 'Name',
    mcp_command: 'Command',
    mcp_args: 'Arguments',
    mcp_env: 'Environment',
    mcp_running: 'Running',
    mcp_stopped: 'Stopped',
    mcp_tools: 'tools',
    mcp_delete: 'Delete',
    mcp_no_servers: 'No MCP servers configured',
  },
  zh: {
    title: '设置',
    section_model: '模型提供方',
    section_appearance: '外观',
    section_about: '关于',
    appearance_note: '仅支持深色 · 浅色即将推出',
    version: '版本',
    github: 'GitHub',
    provider: '提供方',
    model: '模型',
    base: 'Base URL',
    key: 'API KEY',
    change_key: '更换',
    cancel: '取消',
    save: '保存',
    saving: '保存中…',
    close: '关闭',
    language: '语言',
    no_key: '尚未配置',
    has_key: '•••••••• （已保存）',
    custom_model: '自定义模型',
    section_mcp: 'MCP 服务器',
    mcp_add: '添加服务器',
    mcp_name: '名称',
    mcp_command: '命令',
    mcp_args: '参数',
    mcp_env: '环境变量',
    mcp_running: '运行中',
    mcp_stopped: '已停止',
    mcp_tools: '个工具',
    mcp_delete: '删除',
    mcp_no_servers: '未配置 MCP 服务器',
  },
};
