import type { Lang } from '../../types';

export const SETTINGS_COPY: Record<Lang, Record<string, string>> = {
  en: {
    title: 'SETTINGS',
    section_model: 'PROVIDER & MODEL',
    section_appearance: 'APPEARANCE',
    section_about: 'ABOUT',
    appearance_note: 'Dark mode only · light coming soon',
    version: 'Version',
    github: 'GitHub',
    provider: 'PROVIDER',
    model: 'MODEL',
    base: 'BASE URL',
    base_optional: 'optional override',
    base_default: 'using default',
    key: 'API KEY',
    change_key: 'Change',
    cancel: 'Cancel',
    save: 'SAVE',
    saving: 'Saving…',
    close: 'Close',
    language: 'LANGUAGE',
    no_key: 'No key configured',
    has_key: '•••••••• (stored)',
    custom_model: 'Custom model ID',
    section_mcp: 'MCP SERVERS',
    mcp_add: 'Add Server',
    mcp_name: 'Name',
    mcp_command: 'Command',
    mcp_args: 'Arguments',
    mcp_env: 'Environment',
    mcp_running: 'Running',
    mcp_stopped: 'Stopped',
    mcp_tools: 'tools',
    mcp_delete: 'Delete',
    mcp_no_servers: 'No MCP servers configured',
    section_routines: 'ROUTINES',
    routine_add: 'Add Routine',
    routine_name: 'Name',
    routine_prompt: 'Prompt',
    routine_schedule: 'Schedule',
    routine_daily: 'Daily at',
    routine_interval: 'Every N minutes',
    routine_run_now: 'Run Now',
    routine_last_run: 'Last run',
    routine_history: 'History',
    routine_no_routines: 'No routines configured',
    routine_success: 'Success',
    routine_error: 'Error',
    routine_running: 'Running',
    routine_delete: 'Delete',
  },
  zh: {
    title: '设置',
    section_model: '模型提供方',
    section_appearance: '外观',
    section_about: '关于',
    appearance_note: '仅支持深色 · 浅色即将推出',
    version: '版本',
    github: 'GitHub',
    provider: '提供方',
    model: '模型',
    base: 'Base URL',
    base_optional: '可选覆盖',
    base_default: '使用默认',
    key: 'API KEY',
    change_key: '更换',
    cancel: '取消',
    save: '保存',
    saving: '保存中…',
    close: '关闭',
    language: '语言',
    no_key: '尚未配置',
    has_key: '•••••••• （已保存）',
    custom_model: '自定义模型',
    section_mcp: 'MCP 服务器',
    mcp_add: '添加服务器',
    mcp_name: '名称',
    mcp_command: '命令',
    mcp_args: '参数',
    mcp_env: '环境变量',
    mcp_running: '运行中',
    mcp_stopped: '已停止',
    mcp_tools: '个工具',
    mcp_delete: '删除',
    mcp_no_servers: '未配置 MCP 服务器',
    section_routines: '定时任务',
    routine_add: '添加任务',
    routine_name: '名称',
    routine_prompt: '提示词',
    routine_schedule: '计划',
    routine_daily: '每天',
    routine_interval: '每 N 分钟',
    routine_run_now: '立即执行',
    routine_last_run: '上次执行',
    routine_history: '历史',
    routine_no_routines: '未配置定时任务',
    routine_success: '成功',
    routine_error: '失败',
    routine_running: '运行中',
    routine_delete: '删除',
  },
};
